import { NextPage } from 'next'
import React from 'react'
import 'tailwindcss/tailwind.css'
import Sidebar from './Partial/Sidebar'
import Titlebar from './Partial/Titlebar'
import Trendingbar from './Partial/Trendingbar'
import { fullPostModalState, loadingState } from '../atoms/modalAtom'
import { useRecoilValue } from 'recoil'
import { ClipLoader } from 'react-spinners'
import Head from 'next/head'
import { AnimatePresence } from 'framer-motion'
import Modal from './Thread/Modal'

type Props = {
  children: any
}

const Layout: NextPage<Props> = ({ children }) => {
  const loading = useRecoilValue(loadingState)
  const fullModal = useRecoilValue(fullPostModalState)

  return (
    <div className="flex w-full sm:w-[99%] xl:w-[100%]">
      {/* Sidebar */}
      {loading && 
        <div className='fixed w-full h-full left-0 bg-[#03030370] z-50 flex p-10 justify-center '>
          <ClipLoader
            size={60}
            color={"#FFF"}
            loading={loading}
          />
        </div>}
        <AnimatePresence>
          { fullModal && 
              <Modal />
          }
        </AnimatePresence>
      <Sidebar />
      <div className="flex flex-col flex-[2] border-r-[1px] max-w-[37.5rem] " >
        <Titlebar />
        <div className="flex flex-col">
          <Head>
            <title>Twitter Clone</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
            {children}
        </div>
      </div>
      <div className="w-[420px] hidden lg:block">
        <Trendingbar />
      </div>
    </div>
  )
}

export default Layout
